"use client";

/**
 * RiskDisclaimer: the risk and custody terms every user accepts before they
 * get a wallet, shown as cards you swipe through (sign-in page).
 *
 * Legal wording is the approved wording. Only punctuation was changed to the
 * house rules (no em dashes, typographic quotes); the cards group the same
 * clauses by subject. The accepted flag lives in localStorage under
 * DISCLAIMER_KEY and is what the (app) layout checks before letting anyone in.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import { LineIcon } from "@/components/line-icon";

export const DISCLAIMER_KEY = "defi-agent-disclaimer-accepted";

interface Clause {
  label?: string;
  body: React.ReactNode;
}
interface Card {
  title: string;
  important?: boolean;
  intro?: React.ReactNode;
  clauses: Clause[];
  outro?: React.ReactNode;
}

export const RISK_CARDS: Card[] = [
  {
    title: "What you accept",
    intro: (
      <>
        <strong>albicocca</strong> provides access to decentralized finance
        protocols across multiple chains, including swap aggregation,
        cross-chain bridging, lending, security tooling, and an AI assistant. By
        using this application, you acknowledge and accept the
        following&nbsp;risks.
      </>
    ),
    clauses: [],
  },
  {
    title: "Markets and contracts",
    clauses: [
      {
        label: "Market risk",
        body: (
          <>
            Cryptocurrency values are highly volatile and can result in
            significant financial&nbsp;loss.
          </>
        ),
      },
      {
        label: "Smart contract risk",
        body: (
          <>
            DeFi protocols interact with smart contracts that may contain bugs,
            exploits, or governance failures, including those of routing
            aggregators, bridge protocols, and lending markets used by
            this&nbsp;app.
          </>
        ),
      },
      {
        label: "Token approvals",
        body: (
          <>
            Swapping, bridging, and lending require granting ERC-20 spending
            rights to third-party contracts. Unlimited approvals left active are
            a long-term risk vector: use the Security Center to review and
            revoke approvals you no longer&nbsp;need.
          </>
        ),
      },
    ],
  },
  {
    title: "Lending and bridges",
    clauses: [
      {
        label: "Lending protocol risk",
        body: (
          <>
            Supplying assets to lending markets (e.g. Fluid Protocol) exposes
            you to oracle failures, liquidity shortages, frozen reserves, and
            protocol-level insolvency. Past APR rates are not guarantees of
            future returns and can fluctuate or go to&nbsp;zero.
          </>
        ),
      },
      {
        label: "Cross-chain bridge risk",
        body: (
          <>
            Bridge transactions route through third-party protocols (Stargate,
            Across, Hop, and others via LI.FI) and can stall, take longer than
            estimated, or require manual recovery via the bridge’s own
            interface. Funds can remain in transit for extended&nbsp;periods.
          </>
        ),
      },
    ],
  },
  {
    title: "Trading",
    clauses: [
      {
        label: "Leveraged perpetual futures",
        body: (
          <>
            Perpetual futures use borrowed margin and can be liquidated.
            Liquidation can wipe out the entire margin posted to a position.
            Funding is charged continuously while a position stays open. Higher
            leverage increases both potential returns and the risk of rapid,
            total loss of margin. Never use more leverage than you can afford
            to&nbsp;lose.
          </>
        ),
      },
      {
        label: "Slippage & MEV",
        body: (
          <>
            Swap and bridge executions may settle at a different price than
            quoted due to volatility or MEV. MEV protection is best-effort on
            supported chains and is not a&nbsp;guarantee.
          </>
        ),
      },
    ],
  },
  {
    title: "The assistant and its data",
    clauses: [
      {
        label: "AI assistant disclaimer",
        body: (
          <>
            Proposals from the in-app AI assistant are generated by a language
            model and may be inaccurate, outdated, or unsafe. The AI never
            executes without explicit user confirmation.{" "}
            <strong>
              Always verify the chain, token address, and amount before
              approving any&nbsp;action.
            </strong>
          </>
        ),
      },
      {
        label: "Informational data only",
        body: (
          <>
            Smart money signals, KOL/whale activity feeds, leaderboards, token
            safety scans, and DApp phishing checks are <em>educational</em>, not
            financial advice. Security scanners reduce risk but cannot detect
            every exploit; new attacks can pass&nbsp;screening.
          </>
        ),
      },
    ],
  },
  {
    title: "Key custody",
    important: true,
    intro: (
      <>
        Your wallet is powered by <strong>OKX Agentic Wallet</strong>. Private
        keys are generated and stored inside a{" "}
        <strong>Trusted Execution Environment (TEE)</strong>, a
        hardware-isolated secure enclave. This&nbsp;means:
      </>
    ),
    clauses: [
      {
        body: (
          <>
            <strong>
              You cannot export, extract, or back up your private keys.
            </strong>{" "}
            There is no seed phrase, no mnemonic, and no recovery file. This is
            by&nbsp;design.
          </>
        ),
      },
      {
        body: (
          <>
            No one (not you, not OKX, not this application) can access the raw
            private key. All transaction signing happens inside the&nbsp;TEE.
          </>
        ),
      },
      {
        body: (
          <>
            <strong>You depend on OKX infrastructure</strong> to access and
            operate your wallet. If OKX discontinues the Agentic Wallet service,
            you will not be able to recover your keys&nbsp;independently.
          </>
        ),
      },
      {
        body: (
          <>
            Your wallet is linked to the account you sign in with (Google, Apple
            or email). Losing access to that account may result in permanent
            loss of wallet&nbsp;access.
          </>
        ),
      },
    ],
  },
  {
    title: "Your responsibility",
    clauses: [
      {
        label: "Regulatory risk",
        body: (
          <>
            Cryptocurrency regulations vary by jurisdiction and may change at
            any time. You are responsible for compliance with the laws
            applicable to&nbsp;you.
          </>
        ),
      },
    ],
    outro: (
      <>
        This application does not provide financial advice. You are solely
        responsible for your investment decisions. Never invest more than you
        can afford to&nbsp;lose.
      </>
    ),
  },
];

/**
 * The cards, with native scroll snapping (swipe, trackpad, arrow keys) and
 * Previous / Next buttons. `onAllSeen` fires once every card has been on
 * screen, so consent can wait until the whole text was shown.
 */
export function RiskCards({ onAllSeen }: { onAllSeen: () => void }) {
  const trackRef = useRef<HTMLDivElement>(null);
  const [current, setCurrent] = useState(0);
  const seen = useRef(new Set<number>());
  const reported = useRef(false);

  useEffect(() => {
    const track = trackRef.current;
    if (!track) return;
    const cards = Array.from(track.children) as HTMLElement[];
    const io = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (!e.isIntersecting) continue;
          const i = cards.indexOf(
            (e.target as HTMLElement).parentElement as HTMLElement,
          );
          setCurrent(i);
          // The track takes the height of the card in view, so a short card
          // does not sit above an empty block sized for the longest one.
          track.style.height = `${cards[i].offsetHeight}px`;
          seen.current.add(i);
          if (!reported.current && seen.current.size === cards.length) {
            reported.current = true;
            onAllSeen();
          }
        }
      },
      { root: track, threshold: 0.6 },
    );
    // Observe a 1px line at the top of each card: its visibility depends only
    // on the horizontal position, not on the track's current height.
    cards.forEach((c) => {
      const line = c.querySelector(".risk-sentinel");
      if (line) io.observe(line);
    });
    // Until now only the first card had a height (see .risk:not([data-ready])),
    // so fixing the track to it here does not move anything on screen.
    track.style.height = `${cards[0].offsetHeight}px`;
    track.parentElement?.setAttribute("data-ready", "true");
    // Re-measure when the width changes (rotation, window resize).
    const ro = new ResizeObserver(() => {
      const i = Math.round(track.scrollLeft / Math.max(1, track.clientWidth));
      if (cards[i]) track.style.height = `${cards[i].offsetHeight}px`;
    });
    ro.observe(track);
    return () => {
      io.disconnect();
      ro.disconnect();
    };
  }, [onAllSeen]);

  const go = useCallback((i: number) => {
    const track = trackRef.current;
    const card = track?.children[i] as HTMLElement | undefined;
    if (!track || !card) return;
    track.scrollTo({
      left: card.offsetLeft - track.offsetLeft,
      behavior: "smooth",
    });
  }, []);

  const last = RISK_CARDS.length - 1;

  return (
    <div
      className="risk"
      aria-roledescription="carousel"
      aria-label="Risk disclaimer"
    >
      <div className="risk-head">
        <div className="risk-progress" aria-hidden="true">
          {RISK_CARDS.map((c, i) => (
            <span
              key={c.title}
              data-state={i < current ? "done" : i === current ? "on" : "off"}
            />
          ))}
        </div>

        <button
          type="button"
          className="btn btn--sm"
          onClick={() => go(current - 1)}
          disabled={current === 0}
          aria-label="Previous card"
        >
          <LineIcon name="arrow-right" size={16} className="flip" />
        </button>
        <button
          type="button"
          className="btn btn--sm"
          onClick={() => go(current + 1)}
          disabled={current === last}
          aria-label="Next card"
        >
          <LineIcon name="arrow-right" size={16} />
        </button>
      </div>
      <p className="sr-only" aria-live="polite">
        {`${RISK_CARDS[current].title}, card ${current + 1} of ${RISK_CARDS.length}`}
      </p>

      <div
        ref={trackRef}
        className="risk-track"
        tabIndex={0}
        onKeyDown={(e) => {
          if (e.key === "ArrowRight") {
            e.preventDefault();
            go(Math.min(last, current + 1));
          } else if (e.key === "ArrowLeft") {
            e.preventDefault();
            go(Math.max(0, current - 1));
          }
        }}
      >
        {RISK_CARDS.map((card, i) => (
          <section
            key={card.title}
            className="risk-card"
            aria-roledescription="slide"
            aria-label={`${card.title}, ${i + 1} of ${RISK_CARDS.length}`}
          >
            <span className="risk-sentinel" aria-hidden="true" />
            {card.important && <span className="risk-flag">Important</span>}
            <h2 className="risk-title">{card.title}</h2>
            {card.intro && <p className="risk-intro">{card.intro}</p>}
            {card.clauses.length > 0 && (
              <ul className="risk-clauses">
                {card.clauses.map((c, k) => (
                  <li key={k}>
                    {c.label && <h3>{c.label}</h3>}
                    <p>{c.body}</p>
                  </li>
                ))}
              </ul>
            )}
            {card.outro && <p className="risk-outro">{card.outro}</p>}
          </section>
        ))}
      </div>
    </div>
  );
}
