/**
 * RiskDisclaimer — the risk and custody text every user accepts before they
 * get a wallet. Extracted verbatim from the former /welcome flow so the
 * sign-in page can show it; legal wording is unchanged apart from the
 * product name and the sign-in methods (email-only before CLI v4).
 *
 * The accepted flag lives in localStorage under DISCLAIMER_KEY and is what
 * the (app) layout checks before letting anyone in.
 */

export const DISCLAIMER_KEY = "defi-agent-disclaimer-accepted";

export function RiskDisclaimerText() {
  return (
    <>
      <p>
        <strong>albicocca</strong> provides access to decentralized finance protocols across
        multiple chains, including swap aggregation, cross-chain bridging, lending, security
        tooling, and an AI assistant. By using this application, you acknowledge and accept
        the following risks:
      </p>
      <ul className="list-disc pl-4 space-y-1.5">
        <li>
          <strong>Market risk:</strong> Cryptocurrency values are highly volatile and can result in significant financial loss.
        </li>
        <li>
          <strong>Smart contract risk:</strong> DeFi protocols interact with smart contracts that may contain bugs, exploits, or governance failures &mdash; including those of routing aggregators, bridge protocols, and lending markets used by this app.
        </li>
        <li>
          <strong>Lending protocol risk:</strong> Supplying assets to lending markets (e.g. Fluid Protocol) exposes you to oracle failures, liquidity shortages, frozen reserves, and protocol-level insolvency. Past APR rates are not guarantees of future returns and can fluctuate or go to zero.
        </li>
        <li>
          <strong>Cross-chain bridge risk:</strong> Bridge transactions route through third-party protocols (Stargate, Across, Hop, and others via LI.FI) and can stall, take longer than estimated, or require manual recovery via the bridge&rsquo;s own interface. Funds can remain in transit for extended periods.
        </li>
        <li>
          <strong>AI assistant disclaimer:</strong> Proposals from the in-app AI assistant are generated by a language model and may be inaccurate, outdated, or unsafe. The AI never executes without explicit user confirmation &mdash; <strong>always verify the chain, token address, and amount before approving any action.</strong>
        </li>
        <li>
          <strong>Informational data only:</strong> Smart money signals, KOL/whale activity feeds, leaderboards, token safety scans, and DApp phishing checks are <em>educational</em>, not financial advice. Security scanners reduce risk but cannot detect every exploit; new attacks can pass screening.
        </li>
        <li>
          <strong>Token approvals:</strong> Swapping, bridging, and lending require granting ERC-20 spending rights to third-party contracts. Unlimited approvals left active are a long-term risk vector &mdash; use the Security Center to review and revoke approvals you no longer need.
        </li>
        <li>
          <strong>Slippage &amp; MEV:</strong> Swap and bridge executions may settle at a different price than quoted due to volatility or MEV. MEV protection is best-effort on supported chains and is not a guarantee.
        </li>
        <li>
          <strong>Regulatory risk:</strong> Cryptocurrency regulations vary by jurisdiction and may change at any time. You are responsible for compliance with the laws applicable to you.
        </li>
      </ul>

      <div className="bg-destructive/5 border border-destructive/15 rounded-lg p-3 mt-2">
        <p className="font-semibold text-destructive/90 mb-1.5">
          Key Custody &mdash; Important
        </p>
        <p>
          Your wallet is powered by <strong>OKX Agentic Wallet</strong>. Private keys are generated and stored inside a <strong>Trusted Execution Environment (TEE)</strong> &mdash; a hardware-isolated secure enclave. This means:
        </p>
        <ul className="list-disc pl-4 space-y-1 mt-1.5">
          <li>
            <strong>You cannot export, extract, or back up your private keys.</strong> There is no seed phrase, no mnemonic, and no recovery file. This is by design.
          </li>
          <li>
            No one &mdash; not you, not OKX, not this application &mdash; can access the raw private key. All transaction signing happens inside the TEE.
          </li>
          <li>
            <strong>You depend on OKX infrastructure</strong> to access and operate your wallet. If OKX discontinues the Agentic Wallet service, you will not be able to recover your keys independently.
          </li>
          <li>
            Your wallet is linked to the account you sign in with (Google, Apple or email). Losing access to that account may result in permanent loss of wallet access.
          </li>
        </ul>
      </div>

      <p>
        This application does not provide financial advice. You are solely responsible for your investment decisions.
        Never invest more than you can afford to lose.
      </p>
    </>
  );
}
